### PR TITLE
Added 76 icon 

### PR DESCRIPTION
**Pull request by tidalboot**

### CODE REVIEW

**Comment by ryancosans** [comment]
What's the file solder_76?

**Comment by tidalboot** [comment]
It's just the soldier 76 sketch file, not sure why it isn't displaying the .sketch file extension on here. 
Nothing has changed on it but I did have a look at it when I was making the 76 sketch file (as in opened it in Sketch) which has then counted as a "change" to Sketch, then I must have added that "change" in when I was adding files to the staging to be committed. 
That's my bad, didn't see that I had it in there as a changed file, I'll need to pay closer attention to that in the future for sure!
But yeah, it's just where I've opened it, there aren't any real changes to it

**Comment by ryancosans** [comment]
I just noticed the file is called solder XD

**Comment by tidalboot** [comment]
"We're all solders now"

**Pull request merged**
